# Generated by Django 4.1 on 2023-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name2", models.CharField(max_length=250)),
                ("img2", models.ImageField(upload_to="pics2")),
                ("desc2", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="place", old_name="description", new_name="desc",
        ),
    ]
